/*const usersData = axios.get('https://evportal.bashton.ca:27127/getusers')
.then(res => {
  // console.log("res data ==>", data)
  console.log("res data ==>", res)
  return res
})

export default usersData*/

//const usersData = [{"user_id":14,"display_name":"LeShaunJ","first_name":"Arian","last_name":"Johnson","birth_date":"1986-09-06","email_address":"leshaun.john@icloud.com"},{"user_id":17,"display_name":"FS12345","first_name":"Franklin","last_name":"Smith","birth_date":"1990-04-25","email_address":"franklin.smith@gmail.com"},{"user_id":22,"display_name":"theBigBen","first_name":"Ben","last_name":"Ashton","birth_date":"1986-12-12","email_address":"benfordashton@gmail.com"},{"user_id":23,"display_name":"mdjoudi","first_name":"Marc","last_name":"Djoudi","birth_date":"1900-01-01","email_address":"marcdjoudi@gmail.com"},{"user_id":40,"display_name":"user_40","first_name":"Sopheap","last_name":"Cheng","birth_date":"1989-02-22","email_address":"sopheap.cheng5545@gmail.com"},{"user_id":41,"display_name":"SP123","first_name":"Sopheap","last_name":"Cheng","birth_date":"1989-02-22","email_address":"sopheap.cheng123@gmail.com"},{"user_id":42,"display_name":"user_42","first_name":"Sam","last_name":"Vuthy","birth_date":"1975-03-05","email_address":"samvuthy@yahoo.com"},{"user_id":43,"display_name":"Dara.Than","first_name":"Dara","last_name":"Than","birth_date":"1981-04-07","email_address":"dara.than@gmail.com"},{"user_id":44,"display_name":"Soki","first_name":"Sokinarin","last_name":"Lim","birth_date":"1974-10-01","email_address":"Sok.Lim@khmertelecom.com"},{"user_id":46,"display_name":"JM557","first_name":"James","last_name":"Clark","birth_date":"1985-02-25","email_address":"james.clark@yahoo.com"},{"user_id":47,"display_name":"SarahJ","first_name":"Sarah","last_name":"Jefferson","birth_date":"1994-05-22","email_address":"Sarah.Jefferson@gmail.com"},{"user_id":49,"display_name":"user_49","first_name":"LeShaun","last_name":"Johnson","birth_date":"1984-09-10","email_address":"leshaun.john@gmail.com"},{"user_id":50,"display_name":"user_50","first_name":"Jessica","last_name":"Chen","birth_date":"1982-11-29","email_address":"Jessicachen@workez.com"},{"user_id":51,"display_name":"Jchen82","first_name":"Jessica","last_name":"Chen","birth_date":"1982-11-29","email_address":"Jessicachen@work2ez.com"},{"user_id":52,"display_name":"BigPaulie","first_name":"Paul ","last_name":"Febrizio","birth_date":"1979-10-10","email_address":"paulfebrizio@yahoo.com"},{"user_id":70,"display_name":"DJFrico","first_name":"Nicholas","last_name":"Fernandez","birth_date":"1993-04-05","email_address":"nico.fernandez93@icloud.com"},{"user_id":71,"display_name":"user_71","first_name":"Pen","last_name":"Bovathana","birth_date":"1900-01-01","email_address":"pen.bovathana@gmail.com"}]
//export default usersData